config/routes.rb
Rails.application.routes.draw do
  #get 'comments/index'
  #get 'autos/index'
  #get 'bikes/index'
  #get 'cars/index'

  root "cars#index"

  resources :cars do
    resources :comments
  end

  resources :bikes do
    resources :comments
  end

  resources :autos do
    resources :comments
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto.rb
class Auto < ApplicationRecord
	has_many :comments, as: :commentable
end

app/models/bike.rb
class Bike < ApplicationRecord
	has_many :comments, as: :commentable
end

app/models/car.rb
class Car < ApplicationRecord
	has_many :comments, as: :commentable
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :commentable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  def index
      @autos = Auto.all  
  end
  
  def show
    @auto = Auto.find(params[:id])
  end
 
  def new
    @auto = Auto.new
  end

  def create
    @auto = Auto.new(auto_params)
    if @auto.save
      redirect_to @auto
    else
        render :new
    end

  end

  def edit
    @auto = Auto.find(params[:id])
  end

  def update
    @auto = Auto.find(params[:id])
    if @auto.update(auto_params)
      redirect_to @auto
    else
      render :edit
    end

  end

  def destroy
    @auto = Auto.find(params[:id])
    @auto.destroy

    redirect_to root_path
  end

  private
    def auto_params
      params.require(:auto).permit(:name, :city, :date)       
    end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def index
      @bikes = Bike.all  
  end
  
  def show
    @bike = Bike.find(params[:id])
  end
 
  def new
    @bike = Bike.new
  end

  def create
    @bike = Bike.new(bike_params)
    if @bike.save
      redirect_to @bike
    else
        render :new
    end

  end

  def edit
    @bike = Bike.find(params[:id])
  end

  def update
    @bike = Bike.find(params[:id])
    if @bike.update(bike_params)
      redirect_to @bike
    else
      render :edit
    end

  end

  def destroy
    @bike = Bike.find(params[:id])
    @bike.destroy

    redirect_to root_path
  end

  private
    def bike_params
      params.require(:bike).permit(:name, :city, :date)       
    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
      @cars = Car.all  
  end
  
  def show
    @car = Car.find(params[:id])
  end
 
  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    if @car.save
      redirect_to @car
    else
        render :new
    end

  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    if @car.update(car_params)
      redirect_to @car
    else
      render :edit
    end

  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    redirect_to root_path
  end

  private
    def car_params
      params.require(:car).permit(:name, :city, :date)       
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    
    if params[:car_id].present?
      @car = Car.find(params[:car_id])
      @car = Car.find(params[:car_id])
      @comment  = @car.comments.create(comment_params)
      redirect_to car_path(@car)
    elsif params[:bike_id].present?
      @bike = Bike.find(params[:bike_id])
      comment  = @bike.comments.create(comment_params)
      redirect_to bike_path(@bike)
    else
      @auto = Auto.find(params[:auto_id])
      comment  = @auto.comments.create(comment_params)
      redirect_to auto_path(@auto)
    end


    #@bike = Bike.find(params[:bike_id])
   # @comment  = @bike.comments.create(comment_params)
    #redirect_to bike_path(@bike)
  end

  def destroy
    @car = Car.find(params[:car_id])
    @comment = @car.comments.find(params[:id])
    @comment.destroy
    redirect_to car_path(@car)
    
    #@bike = Bike.find(params[:bike_id])
    #@comment = @bike.comments.find(params[:id])
    #@comment.destroy
    #redirect_to bike_path(@bike)

  end
  
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/autos/_form.html.erb
<%= form_with model: @auto do |form| %>
  
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  
  <br>
  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </div>
  
  <br>
  <div>
    <%= form.label :date %><br>
    <%= form.text_field  :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/autos/edit.html.erb
<h1>Edit Auto</h1>  
<%= render "form", auto: @auto %>
<%= link_to "Back to Home page of application",root_path%>

app/views/autos/index.html.erb
<h1>Auto List</h1>
<ul>
	<% @autos.each do |t| %>
		<li>
		  <%= link_to t.name ,t %>
		</li>
	<% end %>
</ul>

<%= link_to "Add New Auto",new_auto_path %>

<br>
<br>

<%= link_to "Back to Home Page",root_path %>

app/views/autos/new.html.erb
<h1>Add New Auto</h1>  
<%= render "form", auto: @auto %>
<%= link_to "Back to Home page Auto",root_path%>

app/views/autos/show.html.erb
<h1><%= @auto.name  %></h1>

<p><%= @auto.city  %></p>

<p><%= @auto.date  %></p>
	
<ul>
  <li><%= link_to "Edit", edit_auto_path(@auto) %></li>

  <li><%= link_to "Delete auto", auto_path(@auto),
                  method: :delete,
                  data: { confirm: "Are you sure You want to delete This auto ?" } %></li>  

  <li><%= link_to "Back", autos_path %></li>
</ul>

<h2>Comments</h2>
<%= render @auto.comments %>

<h2>Add a Comments:</h2>
<%= render 'comments/form2' %>

app/views/bikes/_form.html.erb
<%= form_with model: @bike do |form| %>
  
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  
  <br>
  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </div>
  
  <br>
  <div>
    <%= form.label :date %><br>
    <%= form.text_field  :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Edit Bike</h1>  
<%= render "form", bike: @bike %>
<%= link_to "Back to Home page Bike",root_path%>

app/views/bikes/index.html.erb
<h1>Bike List</h1>
<ul>
	<% @bikes.each do |t| %>
		<li>
		  <%= link_to t.name ,t %>
		</li>
	<% end %>
</ul>

<%= link_to "Add New Bike",new_bike_path %>

app/views/bikes/new.html.erb
<h1>Add New Bike</h1>  
<%= render "form", bike: @bike %>
<%= link_to "Back to Home page Bike",root_path%>

app/views/bikes/show.html.erb
<h1><%= @bike.name  %></h1>

<p><%= @bike.city  %></p>

<p><%= @bike.date  %></p>
	
<ul>
  <li><%= link_to "Edit", edit_bike_path(@bike) %></li>

  <li><%= link_to "Delete bike", bike_path(@bike),
                  method: :delete,
                  data: { confirm: "Are you sure You want to delete This bike ?" } %></li>  

  <li><%= link_to "Back", bikes_path %></li>
</ul>

<h2>Comments</h2>
<%= render @bike.comments %>

<h2>Add a Comments:</h2>
<%= render 'comments/form1' %>

app/views/cars/_form.html.erb
<%= form_with model: @car do |form| %>
  
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>
  
  <br>
  <div>
    <%= form.label :city %><br>
    <%= form.text_field :city %>
  </div>
  
  <br>
  <div>
    <%= form.label :date %><br>
    <%= form.text_field  :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>  
<%= render "form", car: @car %>
<%= link_to "Back to Home page Car",root_path%>

app/views/cars/index.html.erb
<h1>Car List</h1>
<ul>
	<% @cars.each do |t| %>
		<li>
		  <%= link_to t.name ,t %>
		</li>
	<% end %>
</ul>

<%= link_to "Add New Car",new_car_path %>
<br>
<br>

<%= link_to "Add New Bikes",new_bike_path %>

<br>
<br>
<%= link_to "Add New Autos",new_auto_path %>

app/views/cars/new.html.erb
<h1>Add New Car</h1>  
<%= render "form", car: @car %>
<%= link_to "Back to Home page Car",root_path%>

app/views/cars/show.html.erb
<h1><%= @car.name  %></h1>

<p><%= @car.city  %></p>

<p><%= @car.date  %></p>
	
<ul>
  <li><%= link_to "Edit", edit_car_path(@car) %></li>

  <li><%= link_to "Delete car", car_path(@car),
                  method: :delete,
                  data: { confirm: "Are you sure You want to delete This car ?" } %></li>  

  <li><%= link_to "Back", cars_path %></li>
</ul>

<h2>Comments</h2>
<%= render @car.comments %>

<h2>Add a Comments:</h2>
<%= render 'comments/form' %>

app/views/comments/_comment.html.erb
<p>
  <strong>Comments:</strong>
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @car, @car.comments.build ] do |form| %>
  <p>
    <%= form.label :Commets %><br>
    <%= form.text_field :body %>
  </p>

  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_form1.html.erb
<%= form_with model: [ @bike, @bike.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>

  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/_form2.html.erb
<%= form_with model: [ @auto, @auto.comments.build ] do |form| %>
  <p>
    <%= form.label :body %><br>
    <%= form.text_field :body %>
  </p>

  </p>
  
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MoviePolly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>